customhost = "employeedatabase-1.cz2qw08wi23d.eu-north-1.rds.amazonaws.com"
customuser = "Sainath"
custompass = "V.$ehwag219"
customdb = "employeedatabase-1"
custombucket = "addemployee45"
customregion = "eu-north-1b"
